### ISSUE TITLE
Black screen client

### ISSUE THREAD

**Issue by Cryp70m4n** [kyechou/leagueoflegends#18]
Once the game loads the whole client is black, it works you can click play button but everything is black and you can't see anything in client

**Comment by kyechou** [comment]
Disable dxvk (`leagueoflegends del-dxvk`) and then give it a try. I've also disabled it during installation by default.

**Comment by kyechou** [comment]
Also, please make sure that drivers are all installed correctly based on your hardware setup. More information: https://www.reddit.com/r/leagueoflinux/wiki/index#wiki_1_-_.25B6.FE0F_how_to_install_league_of_legends
If it still doesn't work, please provide detailed information similar to those mentioned [here](https://www.reddit.com/r/leagueoflinux/wiki/index#wiki_3b_-_how_to_write_a_support_request_post).

**Comment by trainzkid** [comment]
Sys Info:
Distro: Arch Linux
Kernel: 5.14.14-zen1-1-zen
Window Manager: i3
CPU: AMD Ryzen 7 5700G with Radeon Graphics
RAM: 2382 MB / 23398 MB 
Resolution: 2560x1080

Wine Deps:
wine-staging 6.21-1
giflib 5.2.1-2
lib32-giflib 5.2.1-1
libpng 1.6.37-3
lib32-libpng 1.6.37-3
libldap 2.4.59-2
lib32-libldap 2.4.59-1
gnutls 3.7.2-2
lib32-gnutls 3.7.2-1
mpg123 1.29.2-1
lib32-mpg123 1.29.2-1
openal 1.21.1-1
lib32-openal 1.21.1-1
v4l-utils 1.22.1-1
lib32-v4l-utils 1.20.0-1
libpulse 15.0-1
lib32-libpulse 15.0-1
libgpg-error 1.43-1
lib32-libgpg-error 1.42-1
alsa-plugins 1:1.2.5-2
lib32-alsa-plugins 1.2.5-1
alsa-lib 1.2.5.1-3
lib32-alsa-lib 1.2.5.1-1
libjpeg-turbo 2.1.1-1
lib32-libjpeg-turbo 2.1.1-1
sqlite 3.36.0-1
lib32-sqlite 3.36.0-1
libxcomposite 0.4.5-3
lib32-libxcomposite 0.4.5-1
libxinerama 1.1.4-3
lib32-libgcrypt 1.9.4-1
libgcrypt 1.9.4-1
lib32-libxinerama 1.1.4-1
ncurses 6.3-1
lib32-ncurses 6.3-1
ocl-icd 2.3.1-1
lib32-ocl-icd 2.3.0-1
libxslt 1.1.34-6
lib32-libxslt 1.1.34-2
libva 2.13.0-1
lib32-libva 2.13.0-1
gtk3 1:3.24.30+90+g20be04f7ac-1
lib32-gtk3 3.24.30-1
gst-plugins-base-libs 1.18.5-1
lib32-gst-plugins-base-libs 1.18.4-1
vulkan-icd-loader 1.2.194-1
lib32-vulkan-icd-loader 1.2.194-1

Drivers:
lib32-mesa 21.2.4-1
vulkan-radeon 21.2.4-1
lib32-vulkan-radeon 21.2.4-1
vulkan-icd-loader 1.2.194-1
lib32-vulkan-icd-loader 1.2.194-1

I installed via the Arch AUR package thing. Once the client loads up, the client stays black, even after deleting the DXVK stuff (via del-dxvk). I can still click on things in the client, I hear the hover over sound and can even find the "Play" button at the top left of the screen and the X in the top right just by moving my mouse to where it should be located. The client stays black though, no matter what. I've uninstalled and reinstalled via leagueoflegends uninstall/install to no avail. It's also just the main client, the login section of the client (the bigger window with login and password, as well as the downloading bar) show up correctly, no black there. Obviously, once the login screen goes away and the main client opens up, it's black.

Here's all the output I get when I launch league (via leagueoflegends start).
[lol.log](https://github.com/kyechou/leagueoflegends/files/7517764/lol.log)

And here's the pretty view I get of the client.
![lol-client-blackscreen](https://user-images.githubusercontent.com/25827707/141236790-2e4bad24-89c5-45e7-a229-5dc907557fcb.png)

For reference, here's my entire desktop with the black client included.
![lol-client-blackscreen-fulldesktop](https://user-images.githubusercontent.com/25827707/141238179-bf904484-607a-4051-ac2d-132bcde1f9fc.png)


Hopefully I didn't forget to hide any sensitive info here.

Lemme know if this helps any!!

**Comment by kyechou** [comment]
Perhaps replace `wine-staging` with `wine-lol`, and then remove `lib32-mesa`, since you're already using `lib32-vulkan-radeon` if I understand it correctly. Once it's done, update the `leagueoflegends` AUR package to the latest revision, and then use `leagueoflegends uninstall` and `leagueoflegends install` (or just `leagueoflegends reinstall`) to reinstall it from scratch, which should also install dxvk by default. Hopefully that may help...

**Comment by trainzkid** [comment]
Woops, I thought I included my information about wine-lol since it's required by the leagueoflegends AUR. Sorry about that!

wine-lol 5.18-1

Unfortunately, I can't remove lib32-mesa since it's apparently required by steam (via lib32-libglvnd, which requires lib32-mesa).

It appears the lol AUR package is currently at version leagueoflegends-git 0.11.22.r0.g36c1efc-1, which is the same version I currently have installed.

I'm a little confused, I thought the intent of doing the aforementioned del-dxvk was to _remove_ dxvk. Why would I want to install the dxvk stuff (via lol reinstall)? Unless you mean reinstall, then do the del-dxvk thing again?

**Comment by avahe-kellenberger** [comment]
I had this issue not knowing dxvk came by default, closed the game and ran `leagueoflegends add-dxvk` and started the game again, the issue went away.

**Comment by trainzkid** [comment]
@avahe-kellenberger's fix seems to have worked for me!! Thanks!!
