### ISSUE TITLE
System Error

### ISSUE THREAD

**Issue by othmane00git** [kyechou/leagueoflegends#25]
A critical error has occured and the process must be termianted.
would you like to create a crash dump to aid the developers in troubleshooting this issue? This may take up to 5 minutes.
NOTE: the process may appear unresponsive during this time.

Everytime I pick a champion and when the cooldown ends to launch the game I get this error.
I installed wine from WIneHQ and I have nvidia 495 im on debian 11. any ideas what seems to cause this issue?

**Comment by othmane00git** [comment]
![Screenshot_2021-12-19_00-22-44](https://user-images.githubusercontent.com/95961204/146658407-be96a8be-bacf-4414-8ff6-38cd84d6e32e.png)

**Comment by kyechou** [comment]
First thing is that wine (stable) or wine-staging wouldn't really work. You would want to install [wine-lol from M-Reimer](https://github.com/M-Reimer/wine-lol). For Debian, you can install these two pre-built packages at https://m-reimer.de/wine-lol/debian/ with `sudo dpkg -i <pkgname>.deb`, or you can also build them locally following the instructions.

Second, please make sure all the dependencies and the graphics card drivers are installed and working properly. One thing that can be used to test this is `vulkaninfo`. There are online resources about how to do install appropriate graphics card drivers and Vulkan libraries for different distributions. Once you've made sure that it's all done and `vulkaninfo` is working, please check out the latest commit and run `./package.sh debian` to reinstall the package with updated dependency information (I updated it a couple of days ago). But note that the dependency list is not complete, because it wouldn't be able to know what graphics card you have beforehand, so you'd need to have installed the correct set of drivers/libraries. Then, running `leagueoflegends reinstall` would clean up the previous setup and reinstall everything.

Lastly, if the issue still remains, please take a look at the [issue template](https://github.com/kyechou/leagueoflegends/blob/master/.github/ISSUE_TEMPLATE/default-template.md) and provide detailed information about the system as stated.
