### ISSUE TITLE
Question about recent changes (Arch)

### ISSUE THREAD

**Issue by ThePirate42** [kyechou/leagueoflegends#29]
While I was updating with makepkg, root access was required. I searched online, and it seems that the privileged command disables something in the kernel that would normally speed up 32bit applications, and disabling that is an alternative to the patched glibc (that leagueoflegends-git doesn't require anymore).

Why have you made this change? Affecting performance for all 32bit applications seems worse than just using a patched library. Then again I don't know nothing about how this actually works so maybe there is a good reason, or the information that I found is wrong.

I'm asking because I don't really need lol on this PC, so if the change is actually necessary and the kernel tweak actually slows down things, I would prefer to just uninstall lol.

**Comment by ekistece** [comment]
Use my fork, i have it frozen before the proton switch. I'm a contributor here but i like the glibc approach better also. I added the PKGBUILD to create the arch package. [https://github.com/ekistece/leagueoflegends](url)

**Comment by kyechou** [comment]
Hi @ThePirate42, yes, disabling the parameter is an alternative to the patched glibc, and leagueoflegends-git requires either one of those to work. I'm also aware that disabling the parameter may slow down some 32-bit applications, but I'm not sure how much impact it'd have on performance. The reason why I made this change is because the current version of wine-lol is based on an older version of wine, which has some issues with the recent releases of LoL. But I haven't had time to go through all the required patches for the newer wine and for glibc to make them work with the game. If anyone can help updating and testing M-Reimer's wine-lol to a newer version, I'd be more than happy to switch back to the glibc method.

**Comment by kyechou** [comment]
That'd be great! I'll create a new package `leagueoflegends-ge-git` with `wine-ge-lol` for GloriousEggroll's wine, and revert `leagueoflegends-git` back with the stable wine-lol + wine-lol-glibc approach... (probably over the weekend)
@ekistece If it's okay with you, please send me an email with your AUR username so that I could add you as co-maintainer.

**Comment by ekistece** [comment]
Thank you man! I don't have an AUR accopunt yet, I'll make one when I have time. Your script is really useful and easy to work with btw, lutris always gave me problems for some reason.

**Comment by NyaomiDEV** [comment]
Right now, `leagueoflegends-git` needs `wine-ge-lol` which conflicts with `wine`, `wine-staging` and other `wine` forks. This is not ideal, as `wine-ge-lol` can have problems with ordinary Windows software. The proposed solution is to create an alternative package that does not conflict with the systemwide install of `wine`.

**Comment by kyechou** [comment]
Thanks @NyaomiDEV, yeah that makes sense. Another folk had the same comment at the AUR comment section.

Here are a few changes.

* `wine-ge-lol` is now installed at `/opt/wine-ge-lol`, so it doesn't have conflicts now with wine or other wine variants.
* The main script `leagueoflegends` stays the same for the most part, but now there are two versions of `make install`. `make install` installs the original version, which depends on M-Reimer's `wine-lol` and `wine-lol-glibc`, while `make install-ge` installs the newer version, which depends on `wine-ge-lol` (i.e., GloriousEggroll's wine-ge-custom).
* The AUR PKGBUILD now contains two corresponding split packages: `leagueoflegends-git` and `leagueoflegends-ge-git`.
* During installation, neither of the two `make install` commands will modify any sysctl variables. Instead, when launching the game, the launcher script will exit with error messages asking the user to set the variable manually if necessary.

I hope that works for most people. A minor issue is that the old `wine-lol` does not seem to work anymore (at least not on my setup), but the newer version of `wine-ge-lol` does. Closing this thread for now. Please feel free to open new ones if there are other issues.

**Comment by kyechou** [comment]
Small update. Both packages should work now. Many of the recent issues seem to stem from the driver updates of Nvidia related packages.
