### ISSUE TITLE
Legaue of Legends client doesn't run

### ISSUE THREAD

**Issue by edisionnano** [kyechou/leagueoflegends#39]
### System information

 - Distro: Arch Linux
 - DE/WM: KDE and XFCE
 - CPU: i3-9100F
 - GPU: GTX 1650
 - Graphics card drivers installed: NVIDIA 510.54 from Arch Repos

### Describe the issue
After running `leagueoflegends install`, closing the Riot launcher without logging-in and then running `leagueoflegends start` Riot Launcher opens but upon logging-in nothing happens even after 10 minutes. The terminal only prints this 
![image](https://user-images.githubusercontent.com/26039434/156792333-efe189db-ec81-4c42-aba3-eb53747bb490.png)

### Steps to reproduce
Follow the instructions from the README and try to start leagueoflegends

**Comment by Kitt3120** [comment]
Same here.

OS: Arch Linux
Kernel: 5.16.13-zen1-1-zen x86_64
DE/WM: KDE Plasma 5.24.3
GPU: GeForce RTX 2070 SUPER (Nvidia drivers 510.54)

**Comment by caseyjp11** [comment]
@Kitt3120 Please keep in mind that while YOU and some others are definitely having issues, it is not 'broken' on Linux. My rig, while similar to yours has a big difference: AMD RX550 video. And the script and game work just fine.
Another difference is stock kernel vs. ZEN. While I doubt that is an issue, it is definitely a difference from working on my system to not working on yours.

I'd say this is a bug, but it may be an upstream video driver problem as many are using Lutris and or the GIT script to play without issue. 
Another problem that muddies the water here is different implementations. There are a lot of differences in the Lutris launcher vs. the GIT script. (For instance, the Lutris solution crashes on my system with winsock and NT kernel issues as log errors, while the GIT script throws this error: 
err:vulkan:X11DRV_vkCreateWin32SurfaceKHR Failed to allocate client window for hwnd=0x300ec
...and continues normally at the same point during the game launch.

If I were you I would focus on the Nvidia component. After the timeout is finished, the port is open. The game crashing at that point is during the game client load. There are a lot of potential solutions in the r/leagueoflinux sub involving issues with the Nvidia drivers.

**Comment by Kitt3120** [comment]
> @Kitt3120 Please keep in mind that while YOU and some others are definitely having issues, it is not 'broken' on Linux. My rig, while similar to yours has a big difference: AMD RX550 video. And the script and game work just fine. Another difference is stock kernel vs. ZEN. While I doubt that is an issue, it is definitely a difference from working on my system to not working on yours.
> 
> I'd say this is a bug, but it may be an upstream video driver problem as many are using Lutris and or the GIT script to play without issue. Another problem that muddies the water here is different implementations. There are a lot of differences in the Lutris launcher vs. the GIT script. (For instance, the Lutris solution crashes on my system with winsock and NT kernel issues as log errors, while the GIT script throws this error: err:vulkan:X11DRV_vkCreateWin32SurfaceKHR Failed to allocate client window for hwnd=0x300ec ...and continues normally at the same point during the game launch.
> 
> If I were you I would focus on the Nvidia component. After the timeout is finished, the port is open. The game crashing at that point is during the game client load. There are a lot of potential solutions in the r/leagueoflinux sub involving issues with the Nvidia drivers.

Hey, thanks for the response. Excuse my unprecise phrasing, of course, League is not broken for everyone. Sorry, I was definitely overreacting think. It has definitely something to do with the Nvidia drivers or PipeWire, as I played fine on the same Wine version days before and since then only PipeWire and Nvidia drivers updated. So those two are my points to focus on. The gstreamer errors make me think that it's actually PipeWire.

I am aware of all the Nvidia related issues. I helped the community of r/leagueoflinux resolve some of the problems in the past. One of my posts is actually mentioned here in the GIT Readme at the bottom. I tried some of the known fixes for lutris (which I also needed before), like re-installing Nvidia drivers and disabling dxvk and gl cache, but it's still not working. Have to work on that a bit more, this time it seems to be really tricky! :)

**Comment by edisionnano** [comment]
@Kitt3120 have you tried the 470 Vulkan Dev Beta drivers?

**Comment by Kitt3120** [comment]
> I'm on the stock linux kernel btw
> 
> @Kitt3120 have you tried the 470 Vulkan Dev Beta drivers?

Uh nope, I am on the newest nvidia drivers for arch, which is version 510.54 for me. Do you mean that I should downgrade to 470? I will try that next, currently I am trying it with the newest nvidia-beta drivers (which surprisingly is also version 510.54, but I'll just give it a try anyway)

**Comment by Kitt3120** [comment]
> > Hey, thanks for the response. Excuse my unprecise phrasing, of course, League is not broken for everyone. Sorry, I was definitely overreacting. It has definitely something to do with the Nvidia drivers or PipeWire, as I played fine on the same Wine version days before and since then only PipeWire and Nvidia drivers updated. So those two are my points to focus on. The gstreamer errors make me think that it's actually PipeWire.
> > I am aware of all the Nvidia related issues. I helped the community of r/leagueoflinux resolve some of the problems in the past. One of my posts is actually mentioned here in the repo's Readme at the bottom. I tried some of the known fixes for lutris (which I also needed before), like re-installing Nvidia drivers and disabling dxvk and gl cache, but this time it's still not working. Have to work on that a bit more, this time it seems to be really tricky! :)
> 
> I know what it is like to have something just 'work' and then magically with an update go "pooooof". Did you see my workaround for the pipewire/plumber issues? I posted it here. I too had a crash problem once the new pipewire stuff came out, and switching the wine sink to Alsa (via winetricks) brought everything back. If you bring up winecfg and click on the audio tab, is it hanging? (for between 5-10 seconds before showing the tab's info.) If it is, it is definitely pipewire causing problems. If that tab is accessible with no delay, then I'd guess Nvidia is the issue.

Yes, saw that on reddit and here on the issue tracker. I was a bit confused at first because I did not have the described problems. Coincidentally, I was also helping another guy on reddit installing PipeWire on his system, when I noticed some more differences between his setup and mine. I read the arch wiki article again and turns out that PipeWire changed much since I installed it. Back then, it had a component called PipeWire Media Session. That component has been made modular, is now called Media Session and there's a superior implementation for. That's WirePlumber. But I am still on the PipeWire Media Session implementation, so I am not affected by the WirePlumber issue and PipeWire seems to be running fine for me, I rarely had any problems in the past year since using it. Since I found out yesterday, I no longer think that it's PipeWire anymore. Must be Nvidia.

I didn't try the 470 drivers yet. Wanted to, but caught covid and went testing yesterday. Will try soon x)

**Comment by caseyjp11** [comment]
The pipewire problem happened at .48. I pulled wireplumber and reinstalled the old media session. Then d/g pipewire to .47 and nothing changed. It wasn't until just changing the wine prefix to ALSA that things worked again.

**Comment by edisionnano** [comment]
I'm on regular pulseaudio, not pipewire if it matters

**Comment by caseyjp11** [comment]
> I'm on regular pulseaudio, not pipewire if it matters

And that is where the coding/troubleshooting train leaves my station. I don't know. I haven't used pulse (other than the pipewire-pulse plugin) in quite awhile. Arch as a distro moved over to pipe as the default, and other than some manky Bluetooth connectivity issues that crop up, I haven't had any real issues with it until this update. <shrugs>

Regardless, by changing the sink in the prefix to ALSA, you can eliminate that (or mostly eliminate it) as the source of your crashing. (If it makes no difference to the end result, you can use winetricks to set the sink back to pulse.)

**Comment by Kitt3120** [comment]
I don't know what is happening exactly with my Lutris installation, but I am unable to change the audio driver to alsa using winetricks. Winetricks goes through the process like usually, but if when I open up the wine configuration and navigate to the audio tab, it still shows pulse as the driver. It works on other wine prefixes, so I guess I'll just create a new prefix and install the game over again.

On the other hand, I was able to change the audio driver to alsa for the leagueoflegends git script installation and the behavior is the same. Game crashes after logging in. It shows the League of Legends logo for just a split second before it disappears.

**Comment by Simon-L** [comment]
Hoping I can contribute to this.
I'm on Debian Testing so I'll have to stick to 470. Interestingly I've manually switched to PipeWire recently, it is not default on Debian.

I too am having issues with LoL. I can confirm that winecfg from Lutris doesn't allow selecting alsa. I also note that winetricks seems broken (with a `gst` error which might indicate a sound issue) and prevents switching to alsa.
My current situation is that I have never been able to play a single game, I have started investigating 3 days ago.
Interestingly too is that before I fixed the ICD profile thing, the lavapipe backend was used and despite being slow, distorted and unplayable because of mouse not working I could get to the tutorial.

**Comment by caseyjp11** [comment]
> I too am having issues with LoL. I can confirm that winecfg from Lutris doesn't allow selecting alsa. I also note that winetricks seems broken (with a `gst` error which might indicate a sound issue) and prevents switching to alsa.

The git script works just fine using 'leagueoflegends -v run winetricks' to bring up the winetricks interface. It also ensures that the changes stay with the installation version of things.

As of the latest Systemd updates yesterday, my audio issues seemed to have magically resolved themselves. 

I used winetricks to switch back to pulse and a game restart showed that audio is once again working through the pipewire-pulse plugin as it should. So at this point, it was probably a combination of a pipewire update coupled with systemd (which it needs to run) which was having problems with the audio output.
I'm waiting for another confirmation before requesting this one closed.

**Comment by edisionnano** [comment]
@Kitt3120 did you try 470 yet

**Comment by Kitt3120** [comment]
> @Kitt3120 did you try 470 yet

I wanted to try it yesterday, but I gave up in the end. Was a bit too lazy. I have some packages depending on the current Nvidia drivers. I thought it wouldn't be much work to switch over to 470. But turns out that it's a bit more complicated than I initially thought. I don't know if I'll try, don't want to break my system for this. Maybe I'll give it another try soon.

**Comment by Kitt3120** [comment]
I fixed my League!
Here's my post about it: https://www.reddit.com/r/leagueoflinux/comments/tf12dw/found_another_source_fix_for_league_crashes/

Basically, it was because I had vulkan implementations for AMD gpus installed, even though I am on Nvidia. This can happen accidentally by installing the steam package before Nvidia drivers and using the default options.

**Comment by edisionnano** [comment]
> I fixed my League! Here's my post about it: https://www.reddit.com/r/leagueoflinux/comments/tf12dw/found_another_source_fix_for_league_crashes/
> 
> Basically, it was because I had vulkan implementations for AMD gpus installed, even though I am on Nvidia. This can happen accidentally by installing the steam package before Nvidia drivers and using the default options.

radv and amdvlk installed, never thought of checking the icd files 
![image](https://user-images.githubusercontent.com/26039434/158487858-f62d52d4-3ad1-4f94-b268-ac433d89578a.png)

**Comment by edisionnano** [comment]
Closing as resolved but I believe should be added on the tutorial

**Comment by Simon-L** [comment]
Thanks for reopening, let's get to the bottom of that.

@Kitt3120 @edisionnano Had you tried the solutions involving the `VK_ICD_FILENAMES` before coming to that? It's mentioned on reddit and elsewhere regarding issues with League of Legends, for example [here](https://www.reddit.com/r/leagueoflinux/comments/s54h5q/fixing_lutris_dxvk_issue_on_garuda_linux_to_make/hszzp0y/?utm_source=share&utm_medium=web2x&context=3). The folder contains the known drivers files, it's a hint at what is wrong.

It seems that these driver errors are rather frequent and completely silent. The way I found the exact problem was using `export VK_LOADER_DEBUG=all` then I could see that it was using the wrong loader (and failing afterwards because of the missing 32 bit libs). Let me suggest that the `--verbose` flag could also set that environment variable to `error` or `debug`? So that the errors are more obvious.

**Comment by Kitt3120** [comment]
> Thanks for reopening, let's get to the bottom of that.
> 
> @Kitt3120 @edisionnano Had you tried the solutions involving the `VK_ICD_FILENAMES` before coming to that? It's mentioned on reddit and elsewhere regarding issues with League of Legends, for example [here](https://www.reddit.com/r/leagueoflinux/comments/s54h5q/fixing_lutris_dxvk_issue_on_garuda_linux_to_make/hszzp0y/?utm_source=share&utm_medium=web2x&context=3). The folder contains the known drivers files, it's a hint at what is wrong.
> 
> It seems that these driver errors are rather frequent and completely silent. The way I found the exact problem was using `export VK_LOADER_DEBUG=all` then I could see that it was using the wrong loader (and failing afterwards because of the missing 32 bit libs). Let me suggest that the `--verbose` flag could also set that environment variable to `error` or `debug`? So that the errors are more obvious.
> 

That's very interesting, thanks for sharing. I bet that this would also fix the issue. The question is, why was it able to detect the right driver before the update? As far as I can tell, the bug was introduced with a very small patch Monday or Tuesday of last week.

**Comment by coreybruce** [comment]
I run into this issue even tho the file is there

```
wine: cannot find 'C:\Riot Games\Riot Client\RiotClientServices.exe'
```

**Comment by Kitt3120** [comment]
> I run into this issue even tho the file is there
> 
> ```
> wine: cannot find 'C:\Riot Games\Riot Client\RiotClientServices.exe'
> ```

Did you run the leagueoflegends install command as sudo by any chance? Maybe the file is not accessible for wine.
But thinking about it, that would probably just install the game to the root user.
Have you tried to uninstall and install the game again?

**Comment by coreybruce** [comment]
Nope nevermind I fixed it but now I think my account got banned just for using it on Linux.. Nice lmfao 

F U Riot!

**Comment by Kitt3120** [comment]
> Nope nevermind I fixed it! love how one of my accounts was banned just for using Linux some time ago btw
> 
> F U Riot!

How did you fix it?
Also, regarding your account, Riot stated that despite not officially supporting Linux, they are unbanning people getting a false ban because of wine. You can try to contact the support.

**Comment by coreybruce** [comment]
> > Nope nevermind I fixed it! love how one of my accounts was banned just for using Linux some time ago btw
> > F U Riot!
> 
> How did you fix it? Also, regarding your account, Riot stated that despite not officially supporting Linux, they are unbanning people getting a false ban because of wine. You can try to contact the support.

it installed the game into the wrong location next to drive c instead of being inside it which is where it was looking for it.

Oh I didn't know that was a thing, I could contact them if I really wanted to. Thanks for letting me know! :smile:

**Comment by kyechou** [comment]
> I run into this issue even tho the file is there
> 
> ```
> wine: cannot find 'C:\Riot Games\Riot Client\RiotClientServices.exe'
> ```

I know this is resolved, but please open up a new issue in the future if it is not known to be related to the current issue. Thanks :)

**Comment by kyechou** [comment]
For people in the future who are searching for the solution, [this is it](https://github.com/kyechou/leagueoflegends/issues/39#issuecomment-1068500770).

Additional documentation has been added to README. PRs are appreciated.
