### ISSUE TITLE
Debian 32 bit dependencies for nvidia gpus not listed

### ISSUE THREAD

**Issue by Simon-L** [kyechou/leagueoflegends#41]
These 32 bit libraries were needed for the leagueoflegends script (reimer's wine-lol) to work on Nvidia gpus on Debian testing:
`# apt install libnvidia-glvkspirv:i386 libglx-nvidia0:i386`
I suggest to confirm this and then add these to the readme.

This project and the readme are focused on arch, I just wish that distros were able to agree on more standard package names. From a quick search it seems [lib32-nvidia-utils](https://archlinux.org/packages/multilib/x86_64/lib32-nvidia-utils/) is the package that contains the missing libs, although it's weird that it contains *everything* ?!?

### System information

 - Distro: Debian bookworm
 - DE/WM: Gnome
 - CPU: i7 11800H
 - GPU: rtx 3050
 - Graphics card drivers installed: `nvidia`

```
$ vulkaninfo --summary
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
==========
VULKANINFO
==========

Vulkan Instance Version: 1.3.204


Instance Extensions: count = 13
-------------------------------
...

Devices:
========
GPU0:
	apiVersion         = 4202691 (1.2.195)
	driverVersion      = 1 (0x0001)
	vendorID           = 0x10005
	deviceID           = 0x0000
	deviceType         = PHYSICAL_DEVICE_TYPE_CPU
	deviceName         = llvmpipe (LLVM 13.0.1, 256 bits)
	driverID           = DRIVER_ID_MESA_LLVMPIPE
	driverName         = llvmpipe
	driverInfo         = Mesa 21.3.7 (LLVM 13.0.1)
	conformanceVersion = 0.0.0.0
	deviceUUID         = 00000000-0000-0000-0000-000000000000
	driverUUID         = 00000000-0000-0000-0000-000000000000
```

### Describe the issue

For some setup (laptop with integrated and dedicated gpu in my case), the `VK_ICD_FILENAMES` environment variable is also needed so that the correct GPU is used. Setting that variable to the correct nvidia file and inspecting Vulkan drivers debug messages showed that these libraries were missing. LoL would otherwise only run using the testing vulkan lavapipe backend.

### Steps to reproduce

Debian users with Nvidia gpus, see if you het the same error in vulkaninfo output.
Also try `apt-cache policy libglx-nvidia0:i386` to check if it's already installed.

**Comment by kyechou** [comment]
Thanks for letting me know the package names! Unfortunately I don't have Debian machines to confirm it, and I don't know the required package names for other distributions either (especially graphics related packages), so I'm unable to list all dependencies for all distributions. I will just add a paragraph in README explaining the situation with those two as an example. And hope someone will contribute by sharing the package names for other distribution+graphic card configurations.

Also, because I don't know if Debian/Ubuntu has meta packages for those Vulkan drivers, I'd rather not add specific drivers as hard dependencies in the deb package. Otherwise I'd be happy to.

As for setting `VK_ICD_FILENAMES`, I opened up a new issue tracking the enhancement #42, although I won't have time to implement that in the near future. So if anyone sees this, PRs are appreciated!
