### ISSUE TITLE
Problem with Using MangoHud in League of Legends

### ISSUE THREAD

**Issue by DaFalafels** [kyechou/leagueoflegends#44]
### System information

 - Distro: Arch - EndeavourOS
 - DE/WM: KDE
 - CPU: Intel i9-10900kf
 - GPU: RTX 3080
 - Graphics card drivers installed: nvidia

### Describe the issue

Hello. Thank you for this great installer script, you're awesome, but I have a problem trying to get MangoHud to work with this League of Legends installation. I have tried setting up a .conf file named wine-league of legends.conf in /.config/MangoHud but unfortunately it doesn't work. Whenever I get into a game of League the HUD for MangoHud doesn't show. MangoHud works for me in Steam and Lutris games, but I don't think I am setting it right for this script's installation of League of Legends. Any help would be greatly appreciated.

**Comment by kyechou** [comment]
Hi @DaFalafels, the issue is probably more suitable to be opened at mangohub since it's about the usage of mangohub instead of the LoL script.

According to mangohud's documentation (https://github.com/flightlessmango/MangoHud#normal-usage), you need to prepend mangohud to the line that runs the game. So after installing the script, which is typically at `/usr/bin/leagueoflegends`, you may want to modify it as follows. It's tested to be working.

```diff
diff --git a/leagueoflegends b/leagueoflegends
index 1119727..6baf3b9 100755
--- a/leagueoflegends
+++ b/leagueoflegends
@@ -388,7 +388,7 @@ start_LoL() {

     msg "Starting..."
     save_runes
-    wine "$(winepath -w "$CLIENT_EXE")" \
+    mangohud wine "$(winepath -w "$CLIENT_EXE")" \
         --launch-product=league_of_legends \
         --launch-patchline=live
     wineserver --wait
@@ -440,7 +440,7 @@ start_garena() {
     msg "Starting..."
     save_runes
     export PATH=$OLD_PATH
-    wine "$(winepath -w "$CLIENT_EXE")" $riot_argument
+    mangohud wine "$(winepath -w "$CLIENT_EXE")" $riot_argument
     wineserver --wait
     wait
 }
```
