### ISSUE TITLE
Configurible download location

### ISSUE THREAD

**Issue by mibli** [kyechou/leagueoflegends#63]
Perhaps a configuration file should be available to at least set the install location, could be also asked for during `install` command. I have quite small home partition and install games on m2 drive. Installing in user folder also creates an issue with multi-user installation sharing.

**Comment by kyechou** [comment]
Hi @mibli, for now you may modify the script at `/usr/bin/leagueoflegends` to change the installation path in variable "WINEPREFIX".  Maintaining a configuration file doesn't seem necessary for now due to the amount of configurable parameters and that it still requires the user to modify a file.  But any PRs may be reviewed accepted and if the function is really needed.

**Comment by kyechou** [comment]
@mibli The configuration functionality is added. You may create a file at `~/.config/league.sh` with the following line. Please check out the updated README for more details.

```sh
DATA_HOME="<alternative install location>"
```
