### ISSUE TITLE
Vulkan Driver not searching for nvidia

### ISSUE THREAD

**Issue by elancha98** [kyechou/leagueoflegends#67]
The Riot Client will start normally, however when trying to start League of Legends client, it will insta-crash after showing the
"LEAGUE OF LEGENDS" splash that should appear before the client starts.

Taking a look at the logs, I found this is due to the vulkan driver not looking up for nvidia icds, in fact, from the logs
```
DRIVER:           Searching for driver manifest files
DRIVER:              In following folders:
DRIVER:                 /usr/share/vulkan/icd.d/radeon*
DRIVER:                 /usr/share/vulkan/icd.d/amd*
DRIVER:              Found no files
```

I fixed this by making a copy of `/usr/share/vulkan/icd.d/nvidia_icd.json` in `/usr/share/vulkan/icd.d/amd_nvidia_icd.json`. Yes, I know it is very hacky. But I'm not familiar with vulkan code so I didn't dare to try and include the search for nvidia icd.

**Comment by elancha98** [comment]
No problem, the output is `unset`

**Comment by kyechou** [comment]
Ok.. that's weird. I'll have to test it and see if I can reproduce that. Can you also try to run the game with `leagueoflegends -v -s start` and share the full output log? Thanks!

**Comment by kyechou** [comment]
@elancha98, I couldn't reproduce the issue with my Nvidia setup. Please share the command output mentioned above as well as the details of how you installed the game, launched the game, and the related dependencies installed.

**Comment by elancha98** [comment]
Hey, sorry for not responding, I was out on vacation and I couldn't check. I'm home now so here's the output of an error launch [https://pastebin.com/bqv86SnJ](https://pastebin.com/bqv86SnJ) and of a launch with the hack I made [https://pastebin.com/8sG0dFLv](https://pastebin.com/8sG0dFLv). Hope it helps :)

**Comment by patricstan** [comment]
Hi, so I've got the same problem as @elancha98, tried their fix but didn't work. However, when I've read the logs, there was a difference between our problems, instead of missing AMD drivers, I had missing Intel drivers.
> Searching for driver manifest files
DRIVER:              In following folders:
DRIVER:                 /usr/share/vulkan/icd.d/~radeon*~ intel
DRIVER:                 ~/usr/share/vulkan/icd.d/amd*~
DRIVER:              Found no files

After seeing this, I installed lib32-vulkan-intel and everything worked like a charm. My guess is that there is something regarding Nvidia offloading so the game tries to run on the integrated GPU and if there are no drivers for it, it crashes. 
It is just a guess. If it helps, I could try removing the intel vulkan, switch to Nvidia only in Optimus and try running the game this way, see if something changes.

**Comment by patricstan** [comment]
So I tried to remove the Intel vulkan driver and as you would expect the problem reappeared ( https://pastebin.com/bY60Mh50). However, I was able to make it work by forcing the game to use the Nvidia GPU with
`prime-run leagueoflegends`.

For now, I think a fix would be to either install the vulkan drivers for the iGPU (By default only that one is constantly active on Optimus Laptops) or to  install nvidia-prime and run  `prime-run leagueoflegends start`

**Comment by elancha98** [comment]
I've just tried and I was also able to make it work using `prime-run leagueoflegends`
