### ISSUE TITLE
[Feature request] Ability to launch the client with a specific locale. 

### ISSUE THREAD

**Issue by voidscuttle** [kyechou/leagueoflegends#73]
I'm aware that you can download a different locale for the Riot Client which the script prompts you for. However this does not persist for the League client when launching a mismatching locale e.g. ko_KR on EUW.

It would be nice if we could have a launch flag to define a specific locale. This can be done by adding --locale=en_GB or --locale=ja_JP etc to the leagueclient.exe launch process. 

In the meantime, could you direct me to the correct place to include this in the script? It doesn't seem to call on the leagueclient.exe anywhere; and adding it to the other flags under $SKIP_RIOT doesn't seem to have an effect.

**Comment by kyechou** [comment]
@voidscuttle, the script now starts the `RiotClientServices.exe` instead of `LeagueClient.exe`. You may try adding the locale flag to
https://github.com/kyechou/leagueoflegends/blob/be70be271126c40b2c0cf3bbb282962665bd561f/leagueoflegends#L394
https://github.com/kyechou/leagueoflegends/blob/be70be271126c40b2c0cf3bbb282962665bd561f/leagueoflegends#L398
and
https://github.com/kyechou/leagueoflegends/blob/be70be271126c40b2c0cf3bbb282962665bd561f/leagueoflegends#L458
, and see if that works. It didn't seem to work for me, but I'm not entirely sure. Otherwise, you could also change this line to launch the `LeagueClient.exe` directly. https://github.com/kyechou/leagueoflegends/blob/be70be271126c40b2c0cf3bbb282962665bd561f/leagueoflegends#L132

**Comment by voidscuttle** [comment]
I had the same result with line 394 and 398. Not on Garena so didn't touch 458. None of these worked on their own. In combination with `export CLIENT_EXE="$INSTALL_DIR/Riot Client/RiotClientServices.exe"` however it does seem to have worked. Thanks!

**Comment by kyechou** [comment]
@voidscuttle I've updated the script. You should be able to run `leagueoflegends --locale ko_KR start` now, or any other locale supported by the League client. Since the locale option doesn't seem to be passed through the Riot client, Direct Launch is used for the live version. For PBE access, you'd need to sign out and sign in again.

**Comment by voidscuttle** [comment]
Thank you!
