### ISSUE TITLE
Zombie processes when having the context menu for the riot client system tray notification open during game close

### ISSUE THREAD

**Issue by user8295** [kyechou/leagueoflegends#99]
Game does not close fully (two processes remain running) and continues to take 10% cpu usage, even when then closing the context menu.

Steps to reproduce:
1. Close game via "x" in the titlebar, then confirm exit
2. Right-click the riot client system tray (before it goes away)
3. Two processes will remain running, even when closing the menu by, for example, clicking settings (nothing will open, but the menu will go away)

KWin, Wayland, Plasma, Manjaro
I should probably test this with X11...
This is not an issue with latte, I also tested it with the default system tray.
After about 15 to 20 minutes the two zombie processes will just end.
Interestingly, they are not being marked as "zombie" thought, which implies that the OS thinks they still display something?

Useless screenshot:
![Two processes remain running.](https://user-images.githubusercontent.com/57049654/232632514-da3c97d1-648e-494d-93f8-7253a2b279a9.png)
Edit: Oh, and if you don't care, just close this, it is so fucking minor, great job on this awesome easy installer!

**Comment by kyechou** [comment]
Thanks for the issue!

Yes I noticed that the Riot client now have this behavior. Unfortunately life is catching up on me and I probably won't be able to work on this for a few months. Please leave the issue open and any PR would be appreciated.

Given that they're not zombies (meaning that they simply didn't exit and that they don't necessarily need to be displaying or doing anything), it's either a bug of the Riot client or they intentionally leave them open for whatever reason. Ideally, if the Riot client provides some kind of settings to change the behavior, that'd be the best, though I doubt they do. Otherwise, one way to go about this is to implement some detection heuristic after game exits and kill the wine processes when it happens.

**Comment by EndChapter** [comment]
They added client settings in riot client(not lol client). You can change that setting from client settings.
Unselect "Open Riot Client on startup"
Select "Exit Application"

**Comment by kyechou** [comment]
README updated.
